In [5]:
import polars as pl

caminho_csv = r'..\..\data\v2_ftp\raw\assuntos_recorrentes.csv'
df_assuntos = pl.read_csv(caminho_csv, separator='#')

print(f"Total de linhas e colunas: {df_assuntos.shape}")
display(df_assuntos.head())

Total de linhas e colunas: (89572, 7)

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ numero_proce ┆ assunto     ┆ classe      ┆ inteiro_teo ┆ fato        ┆ direito     ┆ pedido      │
│ sso          ┆ ---         ┆ ---         ┆ r           ┆ ---         ┆ ---         ┆ ---         │
│ ---          ┆ str         ┆ str         ┆ ---         ┆ str         ┆ str         ┆ str         │
│ str          ┆             ┆             ┆ str         ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 5543676.06.2 ┆ DIREITO ADM ┆ PROCESSO    ┆ >>>>>inicio ┆ 2 rua conde ┆ administrat ┆ formulados  │
│ 023.8.09.000 ┆ INISTRATIVO ┆ CÍVEL E DO  ┆ <<<<<       ┆ afonso      ┆ ivo sancion ┆ ante o      │
│ 6            ┆ E OUTRA…    ┆ TRABALHO -… ┆ 1 Rua Conde ┆ celso, n.º… ┆ ador. c…    ┆ exposto e   │
│              ┆             ┆             ┆ A…          ┆             ┆             ┆ p…          │
│ 5050011.89.2 ┆ DIREITO ADM ┆ PROCESSO    ┆ >>>>>inicio ┆ trata-se de ┆ e o perigo  ┆ ante o      │
│ 025.8.09.005 ┆ INISTRATIVO ┆ CÍVEL E DO  ┆ <<<<<       ┆ ação        ┆ de dano ou  ┆ exposto, o  │
│ 1            ┆ E OUTRA…    ┆ TRABALHO -… ┆ 1/8  SENHOR ┆ anulatória  ┆ o risco…    ┆ estado de … │
│              ┆             ┆             ┆ D…          ┆ …           ┆             ┆             │
│ 5886009.11.2 ┆ DIREITO ADM ┆ PROCESSO    ┆ >>>>>inicio ┆ mailto:gabr ┆ administrat ┆ finais      │
│ 025.8.09.001 ┆ INISTRATIVO ┆ CÍVEL E DO  ┆ <<<<<       ┆ ielalmeidad ┆ ivo, especi ┆ diante de   │
│ 1            ┆ E OUTRA…    ┆ TRABALHO -… ┆ Praça CDOR  ┆ ejesus@…    ┆ almente…    ┆ todo o      │
│              ┆             ┆             ┆ Ge…         ┆             ┆             ┆ expos…      │
│ 5590257.75.2 ┆ DIREITO ADM ┆ PROCESSO    ┆ >>>>>inicio ┆ a parte     ┆ 2.1- do     ┆ ante o      │
│ 022.8.09.005 ┆ INISTRATIVO ┆ CÍVEL E DO  ┆ <<<<<       ┆ autora      ┆ dano        ┆ exposto,    │
│ 1            ┆ E OUTRA…    ┆ TRABALHO -… ┆ 1 AO JUÍZO  ┆ ajuizou o   ┆ material    ┆ pede e      │
│              ┆             ┆             ┆ DA…         ┆ pedi…       ┆ como já…    ┆ requer…     │
│ 5747068.93.2 ┆ DIREITO ADM ┆ PROCESSO    ┆ >>>>>inicio ┆ trata-se de ┆ iv.1 – da   ┆ null        │
│ 022.8.09.013 ┆ INISTRATIVO ┆ CÍVEL E DO  ┆ <<<<<       ┆ execução    ┆ nulidade do ┆             │
│ 8            ┆ E OUTRA…    ┆ TRABALHO -… ┆ EXCELENTÍSS ┆ fiscal f…   ┆ auto de…    ┆             │
│              ┆             ┆             ┆ IM…         ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [6]:
# Me foi informado que talvez a coluna de assuntos pudesse
# conter múltiplos assuntos separados por um "@"
df_assuntos.filter(pl.col('assunto').str.contains('@'))

shape: (0, 7)
┌─────────────────┬─────────┬────────┬──────────────┬──────┬─────────┬────────┐
│ numero_processo ┆ assunto ┆ classe ┆ inteiro_teor ┆ fato ┆ direito ┆ pedido │
│ ---             ┆ ---     ┆ ---    ┆ ---          ┆ ---  ┆ ---     ┆ ---    │
│ str             ┆ str     ┆ str    ┆ str          ┆ str  ┆ str     ┆ str    │
╞═════════════════╪═════════╪════════╪══════════════╪══════╪═════════╪════════╡
└─────────────────┴─────────┴────────┴──────────────┴──────┴─────────┴────────┘

In [12]:
nulos = df_assuntos.null_count()
print("Valores Nulos por Coluna:")
display(nulos)

duplicados = df_assuntos.is_duplicated().sum()
print(f"\nLinhas duplicadas no dataset: {duplicados}")

Valores Nulos por Coluna:

shape: (1, 7)
┌─────────────────┬─────────┬────────┬──────────────┬──────┬─────────┬────────┐
│ numero_processo ┆ assunto ┆ classe ┆ inteiro_teor ┆ fato ┆ direito ┆ pedido │
│ ---             ┆ ---     ┆ ---    ┆ ---          ┆ ---  ┆ ---     ┆ ---    │
│ u32             ┆ u32     ┆ u32    ┆ u32          ┆ u32  ┆ u32     ┆ u32    │
╞═════════════════╪═════════╪════════╪══════════════╪══════╪═════════╪════════╡
│ 0               ┆ 0       ┆ 0      ┆ 0            ┆ 0    ┆ 0       ┆ 17498  │
└─────────────────┴─────────┴────────┴──────────────┴──────┴─────────┴────────┘

Linhas duplicadas no dataset: 6

In [7]:
distribuicao_assuntos = (
    df_assuntos.group_by("assunto")
    .len(name="quantidade")
    .sort("quantidade", descending=True)
)

for i, (assunto, _) in enumerate(distribuicao_assuntos.iter_rows(), start=1):
    print(f'{i}: {assunto}')

1: DIREITO CIVIL -> Obrigações -> Espécies de Contratos -> Compra e Venda
2: DIREITO CIVIL -> Obrigações -> Inadimplemento -> Perdas e Danos
3: Finalidade - EXPEDIR ALVARA
4: DIREITO CIVIL -> Sucessões -> Inventário e Partilha
5: DIREITO CIVIL -> Obrigações -> Espécies de Contratos -> Prestação de Serviços
6: DIREITO PROCESSUAL CIVIL E DO TRABALHO -> Jurisdição e Competência -> Competência  -> Competência dos Juizados Especiais
7: DIREITO CIVIL -> Obrigações -> Adimplemento e Extinção -> Pagamento
8: DIREITO CIVIL -> Obrigações -> Espécies de Títulos de Crédito -> Cheque
9: DIREITO DO CONSUMIDOR -> Responsabilidade do Fornecedor -> Rescisão do contrato e devolução do dinheiro
10: DIREITO CIVIL -> Responsabilidade Civil -> Indenização por Dano Material -> Acidente de Trânsito
11: DIREITO ASSISTENCIAL -> Benefício Assistencial (Art. 203,V CF/88) -> Pessoa com Deficiência
12: DIREITO PREVIDENCIÁRIO -> Benefícios em Espécie -> Aposentadoria por Incapacidade Permanente
13: DIREITO CIVIL -> Obrigações -> Espécies de Contratos -> Contratos Bancários
14: DIREITO DO CONSUMIDOR -> Contratos de Consumo -> Transporte Aéreo -> Cancelamento de vôo
15: DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO -> Servidor Público Civil -> Sistema Remuneratório e Benefícios -> Adicional de Horas Extras
16: DIREITO DO CONSUMIDOR -> Contratos de Consumo -> Bancários -> Empréstimo consignado
17: DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO -> Servidor Público Civil -> Regime Estatutário -> Promoção / Ascensão -> Progressão Funcional com Interstício de Doze Meses
18: DIREITO CIVIL -> Família -> Alimentos -> Fixação
19: DIREITO PENAL -> Crimes Previstos na Legislação Extravagante -> Crimes de Tráfico Ilícito e Uso Indevido de Drogas -> Tráfico de Drogas e Condutas Afins
20: DIREITO CIVIL -> Obrigações -> Espécies de Títulos de Crédito -> Cédula de Crédito Bancário
21: DIREITO DO CONSUMIDOR -> Contratos de Consumo -> Cartão de Crédito
22: DIREITO PROCESSUAL CIVIL E DO TRABALHO -> Liquidação / Cumprimento / Execução -> Prisão Civil -> Alimentos
23: DIREITO CIVIL -> Obrigações -> Espécies de Contratos -> Alienação Fiduciária
24: DIREITO CIVIL -> Obrigações -> Espécies de Contratos -> Locação de Imóvel -> Cobrança de Aluguéis - Sem despejo
25: DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO -> Servidor Público Civil -> Sistema Remuneratório e Benefícios -> Piso Salarial
26: DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO -> Servidor Público Civil -> Jornada de Trabalho -> Horas Extras
27: DIREITO CIVIL -> Responsabilidade Civil -> Indenização por Dano Moral -> Direito de Imagem
28: Liquidação / Cumprimento / Execução -> Obrigação de Fazer / Não Fazer
29: Obrigações -> Espécies de Títulos de Crédito -> Nota Promissória
30: DIREITO CIVIL -> Obrigações -> Inadimplemento -> Rescisão / Resolução
31: DIREITO DO CONSUMIDOR -> Responsabilidade do Fornecedor -> Repetição do Indébito
32: DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO -> Servidor Público Civil -> Sistema Remuneratório e Benefícios -> Descontos Indevidos
33: DIREITO PROCESSUAL CIVIL E DO TRABALHO -> Liquidação / Cumprimento / Execução -> Valor da Execução / Cálculo / Atualização -> Juros -> Fazenda Pública
34: DIREITO PREVIDENCIÁRIO -> Benefícios em Espécie -> Aposentadoria por Idade (Art. 48/51) -> Rural (Art. 48/51)
35: DIREITO CIVIL -> Família -> Curatela -> Nomeação
36: DIREITO CIVIL -> Obrigações -> Espécies de Títulos de Crédito -> Duplicata
37: DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO -> Atos Administrativos -> Infração Administrativa -> Multas e demais Sanções
38: DIREITO PREVIDENCIÁRIO -> Benefícios em Espécie -> Aposentadoria por Idade (Art. 48/51) -> Aposentadoria Rural (Art. 48/51)
39: DIREITO CIVIL -> Obrigações -> Inadimplemento -> Correção Monetária
40: DIREITO DO CONSUMIDOR -> Contratos de Consumo -> Transporte Aéreo -> Atraso de vôo
41: DIREITO CIVIL -> Coisas -> Propriedade -> Condomínio em Edifício -> Despesas Condominiais
42: Finalidade - CITACAO
43: DIREITO TRIBUTÁRIO -> Impostos -> IPTU/ Imposto Predial e Territorial Urbano
44: DIREITO DO CONSUMIDOR -> Responsabilidade do Fornecedor -> Indenização por Dano Material
45: DIREITO PROCESSUAL CIVIL E DO TRABALHO -> Liquidação / Cumprimento / Execução -> Obrigação de Fazer / Não Fazer
46: DIREITO CIVIL -> Obrigações -> Espécies de Títulos de Crédito -> Nota Promissória
47: DIREITO DO CONSUMIDOR -> Responsabilidade do Fornecedor -> Indenização por Dano Moral -> Inclusão Indevida em Cadastro de Inadimplentes
48: DIREITO TRIBUTÁRIO -> Impostos -> ISS/ Imposto sobre Serviços
49: DIREITO TRIBUTÁRIO -> Impostos -> ICMS/ Imposto sobre Circulação de Mercadorias -> ICMS/Importação
50: Impostos -> IPTU/ Imposto Predial e Territorial Urbano
51: IPTU/ Imposto Predial e Territorial Urbano
52: nulo

In [8]:
df_assuntos.filter(pl.col('assunto').str.contains('nulo'))

shape: (3, 7)
┌──────────────┬─────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ numero_proce ┆ assunto ┆ classe       ┆ inteiro_teor ┆ fato         ┆ direito      ┆ pedido      │
│ sso          ┆ ---     ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│ ---          ┆ str     ┆ str          ┆ str          ┆ str          ┆ str          ┆ str         │
│ str          ┆         ┆              ┆              ┆              ┆              ┆             │
╞══════════════╪═════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 5297185.81.2 ┆ nulo    ┆ PROCESSO     ┆ >>>>>inicio< ┆ excelência,  ┆ vício        ┆ : ante os   │
│ 023.8.09.005 ┆         ┆ CÍVEL E DO   ┆ <<<<         ┆ conforme já  ┆ redibitório  ┆ fatos e o   │
│ 1            ┆         ┆ TRABALHO -…  ┆ V a l o r :  ┆ expos…       ┆ – prazo par… ┆ direito ex… │
│              ┆         ┆              ┆ …            ┆              ┆              ┆             │
│ 5066030.10.2 ┆ nulo    ┆ PROCESSO     ┆ >>>>>inicio< ┆ a autora é   ┆ de cobrança  ┆ por todo o  │
│ 024.8.09.005 ┆         ┆ CÍVEL E DO   ┆ <<<<         ┆ servidora    ┆ das          ┆ exposto,    │
│ 1            ┆         ┆ TRABALHO -…  ┆ GOUVEIA      ┆ pública …    ┆ diferenças   ┆ requer à …  │
│              ┆         ┆              ┆ RIBEI…       ┆              ┆ re…          ┆             │
│ 5423227.86.2 ┆ nulo    ┆ Procedimento ┆ >>>>>inicio< ┆ o requerente ┆ mediante a   ┆ ante o      │
│ 020.8.09.005 ┆         ┆ do Juizado   ┆ <<<<         ┆ era credor   ┆ deliberada   ┆ exposto,    │
│ 0            ┆         ┆ Especi…      ┆ Avenida      ┆ do re…       ┆ manuten…     ┆ requer a    │
│              ┆         ┆              ┆ Brasi…       ┆              ┆              ┆ voss…       │
└──────────────┴─────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

---
# **Dataset Processado**

In [9]:
import polars as pl

caminho_csv = r'..\..\data\v2_ftp\processed\assuntos_recorrentes_processado.csv'
df_assuntos_processado = pl.read_csv(caminho_csv)

print(f"Total de linhas e colunas: {df_assuntos_processado.shape}")
display(df_assuntos_processado.head())

Total de linhas e colunas: (89569, 2)

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────┐
│ texto_limpo                     ┆ assunto                 │
│ ---                             ┆ ---                     │
│ str                             ┆ str                     │
╞═════════════════════════════════╪═════════════════════════╡
│ 2 rua conde afonso celso n o 5… ┆ Multas e demais Sanções │
│ trata se de acao anulatoria ob… ┆ Multas e demais Sanções │
│ mailto gabrielalmeidadejesus h… ┆ Multas e demais Sanções │
│ a parte autora ajuizou o pedid… ┆ Multas e demais Sanções │
│ trata se de execucao fiscal fu… ┆ Multas e demais Sanções │
└─────────────────────────────────┴─────────────────────────┘

In [10]:
distribuicao_assuntos_processado = (
    df_assuntos_processado.group_by("assunto")
    .len(name="quantidade")
    .sort("quantidade", descending=True)
)

nomes_assuntos = []
for assunto, _ in distribuicao_assuntos_processado.iter_rows():
    nomes_assuntos.append(assunto)

for i, a in enumerate(sorted(nomes_assuntos), start=1):
    print(f'{i}: {a}')

1: Acidente de Trânsito
2: Adicional de Horas Extras
3: Alienação Fiduciária
4: Alimentos
5: Aposentadoria Rural (Art. 48/51)
6: Aposentadoria por Incapacidade Permanente
7: Atraso de vôo
8: Cancelamento de vôo
9: Cartão de Crédito
10: Cheque
11: Cobrança de Aluguéis - Sem despejo
12: Competência dos Juizados Especiais
13: Compra e Venda
14: Contratos Bancários
15: Correção Monetária
16: Cédula de Crédito Bancário
17: Descontos Indevidos
18: Despesas Condominiais
19: Direito de Imagem
20: Duplicata
21: Empréstimo consignado
22: Fazenda Pública
23: Finalidade - CITACAO
24: Finalidade - EXPEDIR ALVARA
25: Fixação
26: Horas Extras
27: ICMS/Importação
28: IPTU/ Imposto Predial e Territorial Urbano
29: ISS/ Imposto sobre Serviços
30: Inclusão Indevida em Cadastro de Inadimplentes
31: Indenização por Dano Material
32: Inventário e Partilha
33: Multas e demais Sanções
34: Nomeação
35: Nota Promissória
36: Obrigação de Fazer / Não Fazer
37: Pagamento
38: Perdas e Danos
39: Pessoa com Deficiência
40: Piso Salarial
41: Prestação de Serviços
42: Progressão Funcional com Interstício de Doze Meses
43: Repetição do Indébito
44: Rescisão / Resolução
45: Rescisão do contrato e devolução do dinheiro
46: Rural (Art. 48/51)
47: Tráfico de Drogas e Condutas Afins