In [2]:
import polars as pl

caminho_csv = r'..\..\data\v2_ftp\raw\classes_recorrentes.csv'

df_classes = pl.read_csv(caminho_csv, separator='#')

print(f"Total de linhas e colunas: {df_classes.shape}")
display(df_classes.head())

Total de linhas e colunas: (49195, 6)

shape: (5, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ numero_process ┆ classe         ┆ inteiro_teor   ┆ fato          ┆ direito       ┆ pedido        │
│ o              ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ ---            ┆ str            ┆ str            ┆ str           ┆ str           ┆ str           │
│ str            ┆                ┆                ┆               ┆               ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 5246168.67.202 ┆ Agravo de      ┆ >>>>>inicio<<< ┆ 5. na origem  ┆ tutelado:     ┆ autorais e,   │
│ 0.8.09.0000    ┆ Instrumento (  ┆ <<
            ┆ trata-se de   ┆ individual    ┆ principalment │
│                ┆ CPC )          ┆ EXCELENTISSI…  ┆ ação…         ┆ homogêne…     ┆ e, o…         │
│ 5651593.10.202 ┆ Agravo de      ┆ >>>>>inicio<<< ┆ a agravada    ┆ , o risco de  ┆ de acordo com │
│ 0.8.09.0000    ┆ Instrumento (  ┆ <<             ┆ ingressou em  ┆ grave dano,   ┆ os            │
│                ┆ CPC )          ┆ EXCELENTÍSSIM… ┆ juízo…        ┆ de di…        ┆ fundamentos … │
│ 5359630.02.202 ┆ Agravo de      ┆ >>>>>inicio<<< ┆ o agravante   ┆ e razões do   ┆ requer de     │
│ 0.8.09.0000    ┆ Instrumento (  ┆ <<             ┆ foi condenado ┆ pedido de     ┆ vossa         │
│                ┆ CPC )          ┆ SOUTO RAMOS &… ┆ em …          ┆ reforma…      ┆ excelência,   │
│                ┆                ┆                ┆               ┆               ┆ o…            │
│ 5514481.96.202 ┆ Agravo de      ┆ >>>>>inicio<<< ┆ a agravante   ┆ fundamental à ┆ a) requer a   │
│ 0.8.09.0000    ┆ Instrumento (  ┆ <<             ┆ demandou uma  ┆ tutela        ┆ vossa         │
│                ┆ CPC )          ┆ Excelentíssim… ┆ ação…         ┆ adequada…     ┆ excelência,…  │
│ 5586664.65.202 ┆ Agravo de      ┆ >>>>>inicio<<< ┆ que a         ┆ . por estes   ┆ null          │
│ 0.8.09.0000    ┆ Instrumento (  ┆ <<             ┆ agravante     ┆ motivos, nos  ┆               │
│                ┆ CPC )          ┆ JURIDICUS ADV… ┆ sofreu um     ┆ termo…        ┆               │
│                ┆                ┆                ┆ gra…          ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [3]:
nulos = df_classes.null_count()
print("Valores Nulos por Coluna:")
display(nulos)

duplicados = df_classes.is_duplicated().sum()
print(f"\nLinhas duplicadas no dataset: {duplicados}")

if duplicados > 0:
    df_classes = df_classes.unique(subset=["numero_processo"], keep="first")
    print(f"Total de linhas após remover duplicatas: {df_classes.shape[0]}")

Valores Nulos por Coluna:

shape: (1, 6)
┌─────────────────┬────────┬──────────────┬──────┬─────────┬────────┐
│ numero_processo ┆ classe ┆ inteiro_teor ┆ fato ┆ direito ┆ pedido │
│ ---             ┆ ---    ┆ ---          ┆ ---  ┆ ---     ┆ ---    │
│ u32             ┆ u32    ┆ u32          ┆ u32  ┆ u32     ┆ u32    │
╞═════════════════╪════════╪══════════════╪══════╪═════════╪════════╡
│ 0               ┆ 0      ┆ 0            ┆ 0    ┆ 0       ┆ 11484  │
└─────────────────┴────────┴──────────────┴──────┴─────────┴────────┘

Linhas duplicadas no dataset: 44
Total de linhas após remover duplicatas: 49168

In [15]:
distribuicao_classes = (
    df_classes.group_by("classe")
    .len(name="quantidade")
    .sort("quantidade", descending=True)
)

print(f"Total de classes únicas: {distribuicao_classes.shape[0]}")
display(distribuicao_classes.tail(10))

for i, (classe, _) in enumerate(distribuicao_classes.iter_rows(), start=1):
    print(f'{i}: {classe}')

Total de classes únicas: 32

shape: (10, 2)
┌─────────────────────────────────┬────────────┐
│ classe                          ┆ quantidade │
│ ---                             ┆ ---        │
│ str                             ┆ u32        │
╞═════════════════════════════════╪════════════╡
│ PROCESSO CÍVEL E DO TRABALHO -… ┆ 1000       │
│ PROCESSO CÍVEL E DO TRABALHO -… ┆ 1000       │
│ Procedimento Comum              ┆ 1000       │
│ Procedimento do Juizado Especi… ┆ 1000       │
│ PROCESSO CÍVEL E DO TRABALHO -… ┆ 1000       │
│ PROCESSO CÍVEL E DO TRABALHO -… ┆ 1000       │
│ PROCESSO CÍVEL E DO TRABALHO -… ┆ 747        │
│ Execução Fiscal                 ┆ 505        │
│ PROCESSO CRIMINAL -> Cartas ->… ┆ 477        │
│ Carta Precatória Cível          ┆ 466        │
└─────────────────────────────────┴────────────┘

1: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Cumprimento de Sentença/Decisão -> Cumprimento de Sentença contra a Fazenda Pública
2: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Regidos por Outros Códigos, Leis Esparsas e Regimentos -> Alvará Judicial - Lei 6858/80
3: PROCESSO CRIMINAL -> Medidas Garantidoras -> Liberdade -> Liberdade Provisória com ou sem fiança
4: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Cumprimento de Sentença/Decisão -> Cumprimento de sentença
5: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Liquidação -> Liquidação de Sentença pelo Procedimento Comum
6: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Especiais de Jurisdição Contenciosa -> Monitória
7: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Regidos por Outros Códigos, Leis Esparsas e Regimentos -> Alimentos - Lei Especial Nº 5.478/68
8: Agravo de Instrumento ( CPC )
9: PROCESSO CÍVEL E DO TRABALHO -> Processo de Execução -> Embargos -> Embargos à Execução
10: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Especiais de Jurisdição Contenciosa -> Inventário
11: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Regidos por Outros Códigos, Leis Esparsas e Regimentos -> Mandado de Segurança Cível
12: PROCESSO CÍVEL E DO TRABALHO -> Tutela Provisória de Urgência e Tutela Provisória de Evidência -> Tutela Antecipada Antecedente
13: PROCESSO CRIMINAL -> Medidas Garantidoras -> Habeas Corpus Criminal
14: PROCESSO CÍVEL E DO TRABALHO -> Outros Procedimentos -> Cartas -> Carta Precatória Cível
15: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Especiais de Jurisdição Voluntária -> Interdição/Curatela
16: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Cumprimento de Sentença/Decisão -> Cumprimento de Sentença de Obrigação de Prestar Alimentos
17: PROCEDIMENTOS PRÉ-PROCESSUAIS DE RESOLUÇÃO CONSENSUAL DE CONFLITOS -> Reclamação Pré-processual
18: Execução de Título Extrajudicial ( L.E. )
19: PROCESSO CRIMINAL -> Recursos -> Apelação Criminal
20: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimento do Juizado Especial Cível
21: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimento do Juizado Especial da Fazenda Pública
22: PROCESSO CÍVEL E DO TRABALHO -> Recursos -> Agravos -> Agravo de Instrumento
23: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimentos Especiais -> Procedimentos Regidos por Outros Códigos, Leis Esparsas e Regimentos -> Busca e Apreensão em Alienação Fiduciária
24: PROCESSO CÍVEL E DO TRABALHO -> Processo de Execução -> Execução de Título Extrajudicial -> Execução de Título Extrajudicial
25: Procedimento Comum
26: Procedimento do Juizado Especial Cível
27: PROCESSO CÍVEL E DO TRABALHO -> Outros Procedimentos -> Atos e expedientes -> Petição Cível
28: PROCESSO CÍVEL E DO TRABALHO -> Processo de Conhecimento -> Procedimento de Conhecimento -> Procedimento Comum Cível
29: PROCESSO CÍVEL E DO TRABALHO -> Processo de Execução -> Execução Fiscal
30: Execução Fiscal
31: PROCESSO CRIMINAL -> Cartas -> Carta Precatória Criminal
32: Carta Precatória Cível

---
# **Dataset Processado**

In [ ]:
import polars as pl

caminho_csv_processado = r'..\..\data\v2_ftp\processed\classes_recorrentes_processado.csv'

df_classes_processado = pl.read_csv(caminho_csv_processado)

print(f"Total de linhas e colunas: {df_classes_processado.shape}")
display(df_classes_processado.head())

Total de linhas e colunas: (49195, 2)

shape: (5, 2)
┌─────────────────────────────────┬───────────────────────────────┐
│ texto_limpo                     ┆ classe                        │
│ ---                             ┆ ---                           │
│ str                             ┆ str                           │
╞═════════════════════════════════╪═══════════════════════════════╡
│ inicio excelentissimo senhor d… ┆ Agravo de Instrumento ( CPC ) │
│ inicio excelentissimo senhor d… ┆ Agravo de Instrumento ( CPC ) │
│ inicio souto ramos batista adv… ┆ Agravo de Instrumento ( CPC ) │
│ inicio excelentissimo a senhor… ┆ Agravo de Instrumento ( CPC ) │
│ inicio juridicus advocacia fra… ┆ Agravo de Instrumento ( CPC ) │
└─────────────────────────────────┴───────────────────────────────┘

In [18]:
distribuicao_classes_processado = (
    df_classes_processado.group_by("classe")
    .len(name="quantidade")
    .sort("quantidade", descending=True)
)

print(f"Total de classes únicas: {distribuicao_classes_processado.shape[0]}")
display(distribuicao_classes_processado.tail(10))

nomes_classes = []
for classe, _ in distribuicao_classes_processado.iter_rows():
    nomes_classes.append(classe)

for i, c in enumerate(sorted(nomes_classes), start=1):
    print(f'{i}: {c}')

Total de classes únicas: 29

shape: (10, 2)
┌─────────────────────────────────┬────────────┐
│ classe                          ┆ quantidade │
│ ---                             ┆ ---        │
│ str                             ┆ u32        │
╞═════════════════════════════════╪════════════╡
│ Monitória                       ┆ 2000       │
│ Execução Fiscal                 ┆ 1252       │
│ Procedimento Comum              ┆ 1000       │
│ Procedimento do Juizado Especi… ┆ 1000       │
│ Procedimento Comum Cível        ┆ 1000       │
│ Execução de Título Extrajudici… ┆ 1000       │
│ Busca e Apreensão em Alienação… ┆ 1000       │
│ Petição Cível                   ┆ 1000       │
│ Agravo de Instrumento           ┆ 1000       │
│ Carta Precatória Criminal       ┆ 477        │
└─────────────────────────────────┴────────────┘

1: Agravo de Instrumento
2: Agravo de Instrumento ( CPC )
3: Alimentos - Lei Especial Nº 5.478/68
4: Alvará Judicial - Lei 6858/80
5: Apelação Criminal
6: Busca e Apreensão em Alienação Fiduciária
7: Carta Precatória Criminal
8: Carta Precatória Cível
9: Cumprimento de Sentença contra a Fazenda Pública
10: Cumprimento de Sentença de Obrigação de Prestar Alimentos
11: Cumprimento de sentença
12: Embargos à Execução
13: Execução Fiscal
14: Execução de Título Extrajudicial
15: Execução de Título Extrajudicial ( L.E. )
16: Habeas Corpus Criminal
17: Interdição/Curatela
18: Inventário
19: Liberdade Provisória com ou sem fiança
20: Liquidação de Sentença pelo Procedimento Comum
21: Mandado de Segurança Cível
22: Monitória
23: Petição Cível
24: Procedimento Comum
25: Procedimento Comum Cível
26: Procedimento do Juizado Especial Cível
27: Procedimento do Juizado Especial da Fazenda Pública
28: Reclamação Pré-processual
29: Tutela Antecipada Antecedente